{% set name = "openfast" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # See https://conda-forge.org/docs/maintainer/adding_pkgs/#source
  # conda-forge requests tar-ball urls instead of git actions for source
  # Use `openssl sha256 file.tar.gz` to get sha256 stamp
  url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
  sha256: cf255e4a26be4a3d3fadebb56f7083b3406db89cf06be6afbb50a76c1b82eac9
  #git_url: https://github.com/openfast/openfast.git
  #git_rev: v{{ version }}
  #git_depth: 1 # (Defaults to -1/not shallow)
  patches:
    - wavetank_implicit.patch

build:
  number: 1

outputs:

  - name: openfast
    version: {{ version }}
    script: build_of.sh  # [not win]
    script: bld_of.bat  # [win]
    build:
      #run_exports:
      #    - {{ pin_subpackage('openfast', max_pin='x.x') }}
      missing_dso_whitelist:
        - "*/libopenfastlib.dll"         # [win]
    requirements:
      build:
        - {{ stdlib("c") }}                       # [not win]
        - {{ compiler('c') }}                     # [not win]
        - {{ compiler('cxx') }}                   # [not win]
        - {{ compiler('fortran') }}               # [not win]
        - {{ compiler('m2w64_c') }}               # [win]
        - {{ compiler('m2w64_cxx') }}             # [win]
        - {{ compiler('m2w64_fortran') }}         # [win]
        - cmake
        - make               # [not win]
        - ninja              # [win]
      host:
        - libgomp            # [not osx]
        - llvm-openmp        # [osx]
        - openblas           # [not win]
        - libblas            # [win]
        - liblapack          # [win]
        #- libcblas
        #- liblapacke    
      run:
        - libgomp            # [not osx]
        - llvm-openmp        # [osx]

    test:
      commands:
        - aerodisk_driver -h
        - aerodyn_driver -h
        - beamdyn_driver -h
        - FAST.Farm -h
        - hydrodyn_driver -h
        - inflowwind_driver -h
        - moordyn_driver -h
        - openfast -h
        - seastate_driver -h
        - sed_driver -h
        - servodyn_driver -h
        - subdyn_driver -h
        - turbsim -h

  - name: openfast-io
    version: {{ version }}
    script: build_io.sh  # [not win]
    script: bld_io.bat  # [win]
    build:
      #noarch: python
      skip: true  # [py<311]
      #script: {{ PYTHON }} -m pip install openfast_io -vv --no-deps --no-build-isolation
    requirements:
      build:
        - cross-python_{{ target_platform }}               # [build_platform != target_platform]
        - python                                           # [build_platform != target_platform]
      host:
        - python       #{{ python_min }}
        - setuptools
        - hatchling
        - hatch-vcs
        - pip
        #- {{ pin_subpackage('openfast', exact=True) }}
      run:
        - python       #>={{ python_min }}
        - numpy
        - pandas
        - ruamel_yaml
        - deepdiff
        #- {{ pin_subpackage('openfast', exact=True) }}

    test:
      imports:
        - openfast_io
      requires:
        - python {{ python_min }}

  - name: pyopenfast
    version: {{ version }}
    script: build_pyof.sh  # [not win]
    script: bld_pyof.bat  # [win]
    build:
      #noarch: python
      skip: true  # [py<311]
      #script: {{ PYTHON }} -m pip install openfast_io -vv --no-deps --no-build-isolation
    requirements:
      build:
        - cross-python_{{ target_platform }}               # [build_platform != target_platform]
        - python                                           # [build_platform != target_platform]
      host:
        - python       #{{ python_min }}
        - setuptools
        - pip
        #- {{ pin_subpackage('openfast', exact=True) }}
      run:
        - python       #>={{ python_min }}
        - numpy
        #- {{ pin_subpackage('openfast', exact=True) }}

    test:
      imports:
        - pyOpenFAST
      requires:
        - python {{ python_min }}

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  feedstock-name: openfast
  recipe-maintainers:
    - deslaughter
    - gbarter
    - andrew-platt
